version: '3.8'

services:
  frontend:
    # 从当前目录下的 frontend 文件夹中的 Dockerfile 构建镜像
    build: ./frontend
    container_name: user-center-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    networks:
      - user-center-network

  backend:
    # 从当前目录下的 backend 文件夹中的 Dockerfile 构建镜像
    build: ./backend
    container_name: user-center-backend
    # 使用 environment 注入环境变量，而不是挂载配置文件
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/guo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
    depends_on:
      - mysql
    restart: always
    networks:
      - user-center-network

  mysql:
    image: mysql:8.0
    container_name: user-center-mysql
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql/tables.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    restart: always
    networks:
      - user-center-network
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=guo

networks:
  user-center-network:
    driver: bridge

volumes:
  mysql-data: